name: tasky
description: Project for the ASPDM's exam
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Dependency injection
  get_it: ^5.0.1

  # State management
  flutter_bloc: ^7.0.0-nullsafety.2
  bloc_test: ^8.0.0-nullsafety.0

  # Equality
  equatable: ^1.2.5

  # Remote API
  dio: ^3.0.10

  # Local cache
  shared_preferences: ^0.5.12+4

  # Firebase
  firebase_core: 0.7.0
  firebase_messaging: ^8.0.0-dev.14
  firebase_dynamic_links: ^0.7.0+1

  # Annotations
  json_annotation: ^3.0.0
  freezed_annotation: ^0.12.0

  # Misc. dependencies
  mockito: ^4.1.3
  connectivity: ^2.0.2
  loading_overlay: ^0.2.1
  package_info: ^0.4.3+2
  app_settings: ^4.0.4
  share: ^0.6.5+4
  easy_localization: ^2.3.3+1
  flutter_feather_icons: ^1.0.3
  sliding_sheet: ^0.4.1
  circular_check_box:
    git:
      url: https://github.com/Supercaly/circular_check_box.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  easy_colors: ^0.0.1+1
  build_runner: ^1.0.0
  freezed: ^0.12.7
  json_serializable: ^3.2.0
  flutter_launcher_icons: ^0.8.1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/ic_launcher.png
