name: aspdm_project
description: Project for the ASPDM's exam
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  # Misc. dependencies
  equatable: ^1.2.5
  provider: ^4.3.2+2
  get_it: ^5.0.1
  package_info: ^0.4.3+2
  mockito: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  easy_colors: ^0.0.1+1

flutter:
  uses-material-design: true