# Workflow that builds the app for all the platforms.
# This workflow run only on push on the master branch.
name: Tasky Build
on:
  push:
    branches:
      - master

jobs:
  build_app:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Setup Project
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: beta
      - run: |
          flutter config --enable-web
          flutter pub get
      - name: Build part files
        run: ./scripts/linux/build_ci.sh

      # Build Android
      - name: Build Debug Android App Bundle
        run: flutter build appbundle --debug

      # Upload build Artifacts
      - name: Upload Android build
        uses: actions/upload-artifact@v2
        with:
          name: android-debug
          path: build/app/outputs/bundle/debug/app-debug.aab

      # Build Web
      - name: Build Web Release
        run: flutter build web --release

      # Upload Webapp to Firebase Hosting
      - name: Upload Webapp to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASPDM_PROJECT }}"
          channelId: live
