name: ASPDM Project CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # SetUp Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          channel: dev

      - name: Install dependencies
        run: flutter pub get

      # Build part files
      - name: Build part files
        run: ./script/linux/build_ci.sh

